opam-version: "2.0"
name: "suchu"
version: "0.8"
maintainer: "printemilio"
authors: ["printemilio"]
license: "MIT"
build: [
  ["dune" "build" "-p" name "-j" jobs]
]
depends: [
  "ocaml" {>= "5.1"}
  "dune" {>= "3.0"}
  "raylib"
  "ctypes"
  "tsdl"
  "tsdl-image"
  "tsdl-ttf"
]
synopsis: "Native, lightweight desktop application language powered by OCaml"
description: """
Suchu creates native, lightweight desktop applications quickly with an
integrated declarative GUI, source modules, native OCaml extensions, and a
native build pipeline.
"""
